# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rec.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScreenSC(object):
    def setupUi(self, ScreenSC):
        ScreenSC.setObjectName("ScreenSC")
        ScreenSC.resize(468, 495)
        ScreenSC.setAutoFillBackground(False)
        ScreenSC.setStyleSheet("background-color: rgb(54, 54, 54);")
        ScreenSC.setDocumentMode(False)
        ScreenSC.setTabShape(QtWidgets.QTabWidget.Rounded)
        ScreenSC.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(ScreenSC)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_2.setBaseSize(QtCore.QSize(40, 0))
        self.label_2.setStyleSheet("color:rgb(202, 202, 202);\n"
"font-size: 20px;\n"
"font: 75 14pt \"Unispace\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        self.startB = QtWidgets.QPushButton(self.centralwidget)
        self.startB.setStyleSheet("background-color:rgb(0, 195, 94);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Tw Cen MT Condensed Extra Bold\";\n"
"border: 2px solid #555;\n"
" border-radius: 10px;\n"
" border-style:nonet;\n"
"")
        self.startB.setObjectName("startB")
        self.verticalLayout.addWidget(self.startB)
        self.StopB = QtWidgets.QPushButton(self.centralwidget)
        self.StopB.setStyleSheet("background-color:rgb(0, 195, 94);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Tw Cen MT Condensed Extra Bold\";\n"
"border: 2px solid #555;\n"
" border-radius: 10px;\n"
" border-style:nonet;")
        self.StopB.setObjectName("StopB")
        self.verticalLayout.addWidget(self.StopB)
        self.timerText = QtWidgets.QLabel(self.centralwidget)
        self.timerText.setMaximumSize(QtCore.QSize(16777207, 50))
        self.timerText.setStyleSheet("color:rgb(202, 202, 202);\n"
"font-size: 20px;\n"
"")
        self.timerText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.timerText.setWordWrap(False)
        self.timerText.setObjectName("timerText")
        self.verticalLayout.addWidget(self.timerText)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pathText = QtWidgets.QLineEdit(self.frame_2)
        self.pathText.setGeometry(QtCore.QRect(70, 10, 300, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathText.sizePolicy().hasHeightForWidth())
        self.pathText.setSizePolicy(sizePolicy)
        self.pathText.setMinimumSize(QtCore.QSize(0, 29))
        self.pathText.setMaximumSize(QtCore.QSize(350, 10))
        self.pathText.setWhatsThis("")
        self.pathText.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pathText.setInputMask("")
        self.pathText.setText("")
        self.pathText.setFrame(True)
        self.pathText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pathText.setObjectName("pathText")
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(450, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 3000))
        self.label.setBaseSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(True)
        self.label.setTabletTracking(False)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(202, 202, 202);\n"
"font-size: 20px;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        ScreenSC.setCentralWidget(self.centralwidget)

        self.retranslateUi(ScreenSC)
        QtCore.QMetaObject.connectSlotsByName(ScreenSC)

    def retranslateUi(self, ScreenSC):
        _translate = QtCore.QCoreApplication.translate
        ScreenSC.setWindowTitle(_translate("ScreenSC", "MainWindow"))
        self.label_2.setText(_translate("ScreenSC", "SCREEN SC"))
        self.startB.setText(_translate("ScreenSC", "Start"))
        self.StopB.setText(_translate("ScreenSC", "Stop"))
        self.timerText.setText(_translate("ScreenSC", "Not Recording"))
        self.pathText.setToolTip(_translate("ScreenSC", "Put output path with name without extention name"))
        self.pathText.setPlaceholderText(_translate("ScreenSC", "Output Path"))
        self.label.setText(_translate("ScreenSC", "Made By FUSEN"))
